name: DailyRewards
author: Halflove
main: me.Halflove.DailyRewards.Main.Main
version: 1.3.7g
softdepend: [PlaceholderAPI]
api-version: 1.16

commands:
  dailyrewards:
    usage: /<command>
    description: Admin master command.
    aliases: [dr, dradmin, drewards]
  reward:
    usage: /<command>
    description: Claim a reward.
    aliases: [claim, rewards, claimreward, claimrewards]