name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
assignees: ""
body:
  - type: textarea
    id: request
    attributes:
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      value: ""
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
      value: ""
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
      value: ""
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      description: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
      value: ""
    validations:
      required: true
